language: objective-c
os: osx
osx_image: xcode9.2

cache:
  - bundler
	- cocoapods
  
before_install:
	- brew install git-crypt
  - bundle install
  
script: 
	- git-crypt unlock <(echo "$GIT_CRYPT" | base64 -D)
  - xcodebuild -project CointrackingBar.xcodeproj -target CointrackingBar build | xcpretty && exit ${PIPESTATUS[0]}
